image: Visual Studio 2017
configuration: Release  

environment:
  SignClientSecret:
    secure: JuZIfeRY/XF5i/9oZFH5cbUIiIuliazF8TaNB5HvRKU=
  SignClientUser:
    secure: uyweGSwxexnLy4dBNleW8tYcXTA291faj34PQV0ePxOTFSa5Cvf50jyICVP9mLGS
  MyGetApiKey:
    secure: w1p7TvDGit5RlN4XKLjDC12Kd43SQ5qwLgRGGXtjfHKX1Yf7ZAOYBW6pLUkPJFJ6
      
init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true

install: 
  - cmd: nuget install SignClient -Version 0.9.0 -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion  

before_build:
  - cmd: msbuild /t:restore xUnit.Devices.sln
  - ps: | 
      nuget install nerdbank.gitversioning -Version 2.1.11 -SolutionDir $Env:APPVEYOR_BUILD_FOLDER -Verbosity quiet -ExcludeVersion  
      $vers = & .\packages\nerdbank.gitversioning\tools\Get-Version.ps1
      $simpVer = $vers.Version
      $doc = Get-Content ".\templates\xunit.devices.templates\source.extension.vsixmanifest"
      $doc | % { $_.Replace("0.9.9", "$simpVer") } | Set-Content ".\templates\xunit.devices.templates\source.extension.vsixmanifest"
      # ProjectTemplates
      $nuGetVer = $vers.NuGetPackageVersion
      $doc = Get-Content ".\templates\xunit.android.template\ProjectTemplate.csproj"
      $doc | % { $_.Replace("0.9.9", "$nuGetVer") } | Set-Content ".\templates\xunit.android.template\ProjectTemplate.csproj"
      $doc = Get-Content ".\templates\xunit.ios.template\ProjectTemplate.csproj"
      $doc | % { $_.Replace("0.9.9", "$nuGetVer") } | Set-Content ".\templates\xunit.ios.template\ProjectTemplate.csproj"
      $doc = Get-Content ".\templates\xunit.uwp.template\ProjectTemplate.csproj"
      $doc | % { $_.Replace("0.9.9", "$nuGetVer") } | Set-Content ".\templates\xunit.uwp.template\ProjectTemplate.csproj"

build:
  verbosity: normal
  parallel: true
  project: xUnit.Devices.sln

after_build:  
  - cmd: msbuild src\xunit.runner.devices\xunit.runner.devices.csproj /t:pack /p:Configuration=Release /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  - cmd: move templates\xunit.devices.templates\bin\Release\*.vsix .
  - ps: '.\SignClient\Sign-Package.ps1'
    
artifacts:
  - path: '*.nupkg'
  - path: '*.vsix'

test: off
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/xunit-xamarin/api/v2/package
  symbol_server: https://www.myget.org/F/xunit-xamarin/symbols/api/v2/package
  api_key:
    secure: w1p7TvDGit5RlN4XKLjDC12Kd43SQ5qwLgRGGXtjfHKX1Yf7ZAOYBW6pLUkPJFJ6
  artifact: /.*\.nupkg/

after_deploy:
  - cmd: curl -X POST --header "X-NuGet-ApiKey:%MyGetApiKey%" --data-binary @xunit.devices.templates.vsix https://www.myget.org/F/xunit-xamarin/vsix/upload

notifications:
- provider: Slack
  incoming_webhook:
    secure: k1oXe/zscPP/vX2kQXYNO1SkIMvN47r8BNA6gkM6z5+I8rKJD+g8C3+pbdARRuzUHAMO5vzD7TXeL6fMt5oIw0QBnuAGNBLx4EsBWllmPyw=
  channel: '#pulse'
  on_build_success: true
  on_build_failure: true