image: Visual Studio 2017
configuration: Release  
  
init:
  - git config --global core.autocrlf input

nuget:
  disable_publish_on_pr: true
  
before_build:
  - cmd: msbuild /t:restore xUnit.Devices.sln
  
build:
  verbosity: normal
  parallel: true
  project: xUnit.Devices.sln

after_build:  
  - cmd: msbuild src\xunit.runner.devices\xunit.runner.devices.csproj /t:pack /p:Configuration=Release /p:PackageOutputPath=%APPVEYOR_BUILD_FOLDER%
  
artifacts:
  - path: '*.nupkg'

test: off
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/xunit-xamarin/api/v2/package
  symbol_server: https://www.myget.org/F/xunit-xamarin/symbols/api/v2/package
  api_key:
    secure: w1p7TvDGit5RlN4XKLjDC12Kd43SQ5qwLgRGGXtjfHKX1Yf7ZAOYBW6pLUkPJFJ6
  artifact: /.*\.nupkg/

notifications:
- provider: Slack
  incoming_webhook:
    secure: k1oXe/zscPP/vX2kQXYNO1SkIMvN47r8BNA6gkM6z5+I8rKJD+g8C3+pbdARRuzUHAMO5vzD7TXeL6fMt5oIw0QBnuAGNBLx4EsBWllmPyw=
  channel: '#pulse'
  on_build_success: true
  on_build_failure: true